import 'dart:isolate';
import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// Provider to interact with the LLM isolate from the UI
final llmIsolateProvider = Provider((ref) => LlmIsolateService());

class LlmIsolateService {
  Isolate? _isolate;
  SendPort? _sendPort;
  final StreamController<String> _tokenStreamController =
      StreamController<String>.broadcast();

  Stream<String> get tokenStream => _tokenStreamController.stream;

  Future<void> init() async {
    final receivePort = ReceivePort();
    _isolate = await Isolate.spawn(_isolateEntrypoint, receivePort.sendPort);

    receivePort.listen((message) {
      if (message is SendPort) {
        _sendPort = message;
      } else if (message is String) {
        if (message == '[DONE]') {
          // Token generation completed
        } else {
          _tokenStreamController.add(message);
        }
      }
    });
  }

  void prompt(String text) {
    if (_sendPort == null) {
      _tokenStreamController.addError("LLM Engine not initialized");
      return;
    }
    _sendPort!.send(text);
  }

  void dispose() {
    _isolate?.kill(priority: Isolate.immediate);
    _tokenStreamController.close();
  }
}

// ==========================================
// BACKGROUND ISOLATE CODE
// ==========================================
void _isolateEntrypoint(SendPort mainSendPort) {
  final isolateReceivePort = ReceivePort();
  mainSendPort.send(isolateReceivePort.sendPort);

  // MOCK NATIVE C++ BINDING:
  // In a real implementation, this would load the FFI bindings to llama.cpp
  // and maintain the native model state in memory.

  isolateReceivePort.listen((message) async {
    if (message is String) {
      // Simulate token generation via FFI pointer
      final tokens = message.split(' ');
      for (final token in tokens) {
        await Future.delayed(
          const Duration(milliseconds: 50),
        ); // Simulating computation
        mainSendPort.send("$token ");
      }

      // Simulate RAG hallucination or actual response
      await Future.delayed(const Duration(milliseconds: 100));
      mainSendPort.send("\n\n(Generated by ORACLE Isolate)");
      mainSendPort.send('[DONE]');
    }
  });
}
